import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
await page.goto('http://localhost:4173/');
await page.waitForTimeout(1200);
const r = () => page.evaluate(() => { const s = document.getElementById('stage'); const b = s.getBoundingClientRect(); return [s.style.transform, b.x, b.y, b.width, b.height, window.scrollY, document.scrollingElement.scrollTop, document.getElementById('app').scrollTop]; });
console.log('boot', await r());
await page.mouse.click(960, 540);
await page.waitForTimeout(900);
console.log('title', await r());
await page.getByText('New Game').click();
await page.waitForTimeout(500);
console.log('creation', await r());
await page.getByText('Walk Into the Burnlands').click();
await page.waitForTimeout(500);
await page.getByText('Skip').click();
await page.waitForTimeout(700);
console.log('world', await r());
await page.evaluate(() => { const G = window.__G; G.ui.scene = null; G.game.pending = []; G.game.warband = 30; window.__api.emit(); });
await page.waitForTimeout(600);
await page.evaluate(() => { window.__api.startArmy({ region: 'deadspan', attacker: 'player', defender: 'dust', playerAttacking: true, allied: 20, enemy: 40 }); });
await page.waitForTimeout(1500);
console.log('army', await r()); await page.screenshot({ path: '/tmp/claude-0/shots/dbg_army.png' }); console.log(await page.evaluate(() => { const c = document.querySelector('canvas.battle-canvas'); const b = c.getBoundingClientRect(); return [c.width, c.height, b.x, b.y, b.width, b.height, document.body.scrollHeight]; }));
await browser.close();
