import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message + '\n' + e.stack));
page.on('console', (m) => { if (m.type() === 'error') errors.push('CONSOLE ' + m.text()); });
await page.goto('http://localhost:4173/');
await page.waitForTimeout(1500);
await page.mouse.click(960, 540);
await page.waitForTimeout(1000);
await page.getByText('New Game').click();
await page.waitForTimeout(600);
await page.getByText('Walk Into the Burnlands').click();
await page.waitForTimeout(600);
await page.getByText('Skip').click();
await page.waitForTimeout(800);
// skip the tutorial: close the scene, advance the quest
await page.evaluate(() => { const G = window.__G; G.ui.scene = null; G.game.quest.stage = 1; G.game.pending = []; G.ui.selected = 'hopesrest'; window.__api.emit(); });
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/claude-0/shots/11_world.png' });
await page.evaluate(() => { window.__G.ui.selected = 'emberroad'; window.__api.emit(); });
await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/claude-0/shots/12_world_select.png' });
await page.evaluate(() => { window.__G.ui.selected = 'hopesrest'; window.__api.goto('settlement'); });
await page.waitForTimeout(1200);
await page.screenshot({ path: '/tmp/claude-0/shots/13_settlement.png' });
await page.evaluate(() => { window.__api.setTab('bar'); });
await page.waitForTimeout(1200);
await page.screenshot({ path: '/tmp/claude-0/shots/14_saloon.png' });
await page.evaluate(() => { window.__api.setTab('market'); });
await page.waitForTimeout(1200);
await page.screenshot({ path: '/tmp/claude-0/shots/15_market.png' });
await page.evaluate(() => { window.__api.openPanel('crew'); });
await page.waitForTimeout(1200);
await page.screenshot({ path: '/tmp/claude-0/shots/16_crew.png' });
await page.evaluate(() => { window.__api.openPanel('factions'); });
await page.waitForTimeout(1200);
await page.screenshot({ path: '/tmp/claude-0/shots/17_factions.png' });
await page.evaluate(() => { window.__api.openPanel('journal'); });
await page.waitForTimeout(1000);
await page.screenshot({ path: '/tmp/claude-0/shots/18_journal.png' });
console.log(errors.join('\n'));
await browser.close();
