import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push('CONSOLE ' + m.text()); });
await page.goto('http://localhost:4173/');
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/claude-0/shots/01_boot.png' });
await page.mouse.click(960, 540);
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/claude-0/shots/02_title.png' });
await page.getByText('New Game').click();
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/claude-0/shots/03_creation.png' });
await page.getByText('Walk Into the Burnlands').click();
await page.waitForTimeout(2500);
await page.screenshot({ path: '/tmp/claude-0/shots/04_intro.png' });
await page.getByText('Skip').click();
await page.waitForTimeout(2000);
await page.screenshot({ path: '/tmp/claude-0/shots/05_arrival.png' });
console.log(errors.join('\n'));
await browser.close();
